version = 0.1

[default.deploy.parameters]
stack_name = "peak-wallet"
resolve_s3 = true
s3_prefix = "peak-wallet"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
